### ISSUE TITLE
"IndexError: tuple index out of range" on master

### ISSUE THREAD

**Issue by colindean** [stribika/sshlabs#7]
```
$ time python3 scanner.py --instructions --fast myhost:####
Scanning myhost:#### ...
Traceback (most recent call last):
  File "scanner.py", line 248, in <module>
    main()
  File "scanner.py", line 128, in main
    result.issues += analysis.analyze_dh_groups(result.dh_gex_groups, args.fast)
  File "/Users/colin/Source/sshlabs/main/analysis.py", line 167, in analyze_dh_groups
    issues.append(issue_kex_dh_gex_small_group(Severity.warning, group, size))
  File "/Users/colin/Source/sshlabs/main/algorithms.py", line 82, in issue_kex_dh_gex_small_group
    forward secrecy.""".format(size),
IndexError: tuple index out of range

real    19m12.023s
user    0m5.985s
sys 0m2.102s
```

**Comment by colindean** [comment]
Works fine against another host with a far simpler configuration.
